[package]
name = "dabbalist"
version = "0.1.0"
authors = ["Alec Newman <alecnwmn904@gmail.com>"]

[dependencies]
iron = "*"
html = { git = "https://github.com/rovaughn/rust-html" }
router = "*"
mime = "*"
postgres = "*"
r2d2 = "*"
r2d2_postgres = "*"

